# Generated by Django 2.1.5 on 2019-12-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaidinvoice',
            name='bg_isrejected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paidinvoice',
            name='bg_isrejected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalpaidinvoice',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paidinvoice',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
