# Generated by Django 2.1.5 on 2019-12-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paids', '0002_auto_20191219_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaidinvoice',
            name='comentarios_audit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paidinvoice',
            name='comentarios_audit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
