# Generated by Django 2.1.5 on 2020-01-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paids', '0003_auto_20191220_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaidinvoicedetail',
            name='valor_ajuste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='paidinvoicedetail',
            name='valor_ajuste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
