# Generated by Django 2.1.5 on 2020-02-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paids', '0004_auto_20200108_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paidinvoice',
            options={'managed': True, 'ordering': ['fecha_emision'], 'verbose_name_plural': 'Facturas Servicios'},
        ),
        migrations.AddField(
            model_name='historicalpaidinvoice',
            name='audit_user',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='paidinvoice',
            name='audit_user',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
