# Generated by Django 3.1.1 on 2020-09-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paids', '0005_auto_20200217_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paidinvoice',
            options={'managed': True, 'ordering': ['-id_documento_pago'], 'verbose_name_plural': 'Facturas Servicios'},
        ),
    ]
