# Generated by Django 2.2 on 2021-05-31 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('identificacion_proveedor', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('tipo_provedor', models.CharField(default='NACIONAL', max_length=13)),
                ('moneda_transaccion', models.CharField(max_length=10)),
                ('categoria', models.CharField(max_length=250)),
                ('comentarios', models.CharField(blank=True, max_length=250, null=True)),
                ('id_user', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('date_create', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['tipo_provedor', 'nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalSupplier',
            fields=[
                ('identificacion_proveedor', models.CharField(db_index=True, max_length=16)),
                ('nombre', models.CharField(db_index=True, max_length=60)),
                ('tipo_provedor', models.CharField(default='NACIONAL', max_length=13)),
                ('moneda_transaccion', models.CharField(max_length=10)),
                ('categoria', models.CharField(max_length=250)),
                ('comentarios', models.CharField(blank=True, max_length=250, null=True)),
                ('id_user', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('date_create', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical supplier',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
