# Generated by Django 2.2 on 2021-11-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20211122_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplier',
            name='id_proveedor',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
