from .TagsListTemplateView import TagsListTemplateView
from .TagsOrderTemplateView import TagsOrderTemplateView
from .ManagerTemplateView import ManagerTemplateView
from .LabelTemplateView import LabelTemplateView