# Generated by Django 2.1.5 on 2019-02-14 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManager',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('id_registro', models.CharField(max_length=10)),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('nombre_fichero', models.CharField(max_length=125)),
                ('obserbaciones', models.TextField(blank=True, default=None, null=True)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gestion de Archivos',
                'db_table': 'gestor_archivos',
            },
        ),
    ]
