# Generated by Django 2.1.5 on 2019-02-14 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanager',
            name='modelo',
            field=models.ForeignKey(db_column='model', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
