# Generated by Django 2.1.5 on 2019-02-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_auto_20190214_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanager',
            name='bg_isvalid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filemanager',
            name='bg_isvisible',
            field=models.BooleanField(default=True),
        ),
    ]
