from orders.views.OrderSaleTemplateView import OrderSaleTemplateView
from orders.views.CompleteOrderTemplateView import CompleteOrderTemplateView
from orders.views.OrdersListView import OrdersListView