# Generated by Django 2.1.5 on 2019-12-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinfoinvoice',
            name='comentarios_audit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infoinvoice',
            name='comentarios_audit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
