# Generated by Django 2.1.3 on 2022-06-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartial',
            name='bg_status_documents_cfs',
            field=models.TextField(choices=[('PENDING', 'PENDING'), ('SENDED', 'SENDED')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='partial',
            name='bg_status_documents_cfs',
            field=models.TextField(choices=[('PENDING', 'PENDING'), ('SENDED', 'SENDED')], default=None, null=True),
        ),
    ]
