# Generated by Django 2.1.3 on 2022-09-21 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_auto_20220616_1714'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20220916_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLabel',
            fields=[
                ('id_label', models.IntegerField(blank=True, db_index=True)),
                ('initial_range', models.CharField(db_index=True, max_length=15, verbose_name='Rango Inicial')),
                ('end_range', models.CharField(db_index=True, max_length=15, verbose_name='Rango Final')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('parcial', models.SmallIntegerField(default=0, verbose_name='Parcial')),
                ('notas', models.TextField(blank=True, default=None, null=True)),
                ('response', models.TextField(blank=True, default=None, null=True)),
                ('message', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('sign', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('message_status', models.TextField(blank=True, default=None, null=True)),
                ('checked_reverse', models.BooleanField(default=False)),
                ('concordance', models.BooleanField(default=False)),
                ('difference', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('validated_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('activated_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('signed_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('bg_status', models.CharField(choices=[('I', 'Inactive'), ('S', 'Sended'), ('F', 'Signed'), ('A', 'Active'), ('D', 'Disabled'), ('R', 'Rejected'), ('E', 'Error'), ('V', 'Validated')], default='I', max_length=15, verbose_name='Estado')),
                ('id_user', models.SmallIntegerField(default=0)),
                ('date_created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('last_updated', models.DateTimeField(blank=True, editable=False, verbose_name='Ultima Actualización')),
                ('last_jwt', models.TextField(blank=True, default=None, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_factura_detalle', models.ForeignKey(blank=True, db_column='detalle_pedido_factura', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.OrderInvoiceDetail')),
            ],
            options={
                'verbose_name': 'historical label',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOneLabel',
            fields=[
                ('id_one_label', models.IntegerField(blank=True, db_index=True, verbose_name='id etqueta sola')),
                ('code_label', models.CharField(max_length=10, verbose_name='codigo etiqueta')),
                ('notas', models.TextField(blank=True, default=None, null=True, verbose_name='observaciones')),
                ('response', models.TextField(blank=True, default=None, null=True, verbose_name='Respuesta servidor')),
                ('message', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='mensaje enviado')),
                ('sign', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='firma mesaje')),
                ('message_status', models.TextField(blank=True, default=None, null=True, verbose_name='estado mensaje')),
                ('validated_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='validado el')),
                ('activated_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='activado el')),
                ('signed_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='firmado el')),
                ('bg_status', models.CharField(choices=[('I', 'Inactive'), ('S', 'Sended'), ('F', 'Signed'), ('A', 'Active'), ('D', 'Disabled'), ('R', 'Rejected'), ('E', 'Error'), ('V', 'Validated')], default='I', max_length=15, verbose_name='Estado')),
                ('id_user', models.SmallIntegerField(default=0)),
                ('date_created', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('last_updated', models.DateTimeField(blank=True, editable=False, verbose_name='Ultima Actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cod_contable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.Product')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical one label',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id_label', models.AutoField(primary_key=True, serialize=False)),
                ('initial_range', models.CharField(max_length=15, unique=True, verbose_name='Rango Inicial')),
                ('end_range', models.CharField(max_length=15, unique=True, verbose_name='Rango Final')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('parcial', models.SmallIntegerField(default=0, verbose_name='Parcial')),
                ('notas', models.TextField(blank=True, default=None, null=True)),
                ('response', models.TextField(blank=True, default=None, null=True)),
                ('message', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('sign', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('message_status', models.TextField(blank=True, default=None, null=True)),
                ('checked_reverse', models.BooleanField(default=False)),
                ('concordance', models.BooleanField(default=False)),
                ('difference', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('validated_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('activated_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('signed_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('bg_status', models.CharField(choices=[('I', 'Inactive'), ('S', 'Sended'), ('F', 'Signed'), ('A', 'Active'), ('D', 'Disabled'), ('R', 'Rejected'), ('E', 'Error'), ('V', 'Validated')], default='I', max_length=15, verbose_name='Estado')),
                ('id_user', models.SmallIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualización')),
                ('last_jwt', models.TextField(blank=True, default=None, null=True)),
                ('id_factura_detalle', models.ForeignKey(db_column='detalle_pedido_factura', on_delete=django.db.models.deletion.CASCADE, to='orders.OrderInvoiceDetail')),
            ],
        ),
        migrations.CreateModel(
            name='OneLabel',
            fields=[
                ('id_one_label', models.AutoField(primary_key=True, serialize=False, verbose_name='id etqueta sola')),
                ('code_label', models.CharField(max_length=10, verbose_name='codigo etiqueta')),
                ('notas', models.TextField(blank=True, default=None, null=True, verbose_name='observaciones')),
                ('response', models.TextField(blank=True, default=None, null=True, verbose_name='Respuesta servidor')),
                ('message', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='mensaje enviado')),
                ('sign', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='firma mesaje')),
                ('message_status', models.TextField(blank=True, default=None, null=True, verbose_name='estado mensaje')),
                ('validated_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='validado el')),
                ('activated_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='activado el')),
                ('signed_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='firmado el')),
                ('bg_status', models.CharField(choices=[('I', 'Inactive'), ('S', 'Sended'), ('F', 'Signed'), ('A', 'Active'), ('D', 'Disabled'), ('R', 'Rejected'), ('E', 'Error'), ('V', 'Validated')], default='I', max_length=15, verbose_name='Estado')),
                ('id_user', models.SmallIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualización')),
                ('cod_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product')),
            ],
        ),
    ]
