# Generated by Django 2.1.3 on 2022-06-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_auto_20220623_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallabel',
            name='bg_status',
            field=models.CharField(choices=[('I', 'Inactive'), ('S', 'Sended'), ('A', 'Active'), ('D', 'Disabled'), ('R', 'Rejected'), ('E', 'Error'), ('V', 'Validated')], default='I', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='label',
            name='bg_status',
            field=models.CharField(choices=[('I', 'Inactive'), ('S', 'Sended'), ('A', 'Active'), ('D', 'Disabled'), ('R', 'Rejected'), ('E', 'Error'), ('V', 'Validated')], default='I', max_length=15, verbose_name='Estado'),
        ),
    ]
