# Generated by Django 2.1.3 on 2022-06-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0005_auto_20220625_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallabel',
            name='checked_reverse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicallabel',
            name='concordance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicallabel',
            name='difference',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicallabel',
            name='response',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicallabel',
            name='sign',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='checked_reverse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='label',
            name='concordance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='label',
            name='difference',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='response',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='sign',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
