# Generated by Django 2.1.3 on 2022-06-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0006_auto_20220630_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallabel',
            name='message_status',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='message_status',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
