# Generated by Django 2.1.3 on 2022-06-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0007_auto_20220630_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallabel',
            name='activated_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicallabel',
            name='signed_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicallabel',
            name='validated_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='activated_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='signed_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='validated_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
