# Generated by Django 2.1.3 on 2022-06-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0008_auto_20220630_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallabel',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
