# Generated by Django 2.1.3 on 2022-07-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0010_auto_20220705_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallabel',
            name='message_status',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='message_status',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
