# Generated by Django 2.2 on 2021-10-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='nro_proforma',
            field=models.CharField(blank=True, default=0, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='nro_proforma',
            field=models.CharField(blank=True, default=0, max_length=25, null=True),
        ),
    ]
