# Generated by Django 2.1.5 on 2019-12-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderinvoice',
            name='audit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalorderinvoice',
            name='bg_audit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalorderinvoice',
            name='bg_isrejected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='audit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='bg_audit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='bg_isrejected',
            field=models.IntegerField(default=0),
        ),
    ]
