# Generated by Django 2.1.5 on 2020-02-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191223_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderinvoice',
            name='audit_user',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='audit_user',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
