# Generated by Django 2.2 on 2021-10-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211004_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='flete_aduana',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='incoterm',
            field=models.CharField(blank=True, choices=[('FOB', 'FOB'), ('FCA', 'FCA'), ('CPT', 'CPT'), ('EXW', 'EXW')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='regimen',
            field=models.CharField(choices=[('10', '10'), ('70', '70')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='seguro_aduana',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='flete_aduana',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='incoterm',
            field=models.CharField(blank=True, choices=[('FOB', 'FOB'), ('FCA', 'FCA'), ('CPT', 'CPT'), ('EXW', 'EXW')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='regimen',
            field=models.CharField(choices=[('10', '10'), ('70', '70')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='seguro_aduana',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
