# Generated by Django 2.2 on 2021-05-31 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210531_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 31, 19, 53, 14, 164995, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 31, 19, 53, 14, 164995, tzinfo=utc), null=True),
        ),
    ]
