# Generated by Django 2.2 on 2021-10-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211015_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='incoterm',
            field=models.CharField(blank=True, choices=[('FOB', 'FOB'), ('FCA', 'FCA'), ('CPT', 'CPT'), ('EXW', 'EXW'), ('CFR', 'CFR')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='incoterm',
            field=models.CharField(blank=True, choices=[('FOB', 'FOB'), ('FCA', 'FCA'), ('CPT', 'CPT'), ('EXW', 'EXW'), ('CFR', 'CFR')], max_length=4, null=True),
        ),
    ]
