# Generated by Django 2.1.3 on 2022-05-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20211018_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderinvoice',
            name='bg_have_tags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='bg_have_tags',
            field=models.BooleanField(default=False),
        ),
    ]
