# Generated by Django 2.1.3 on 2022-06-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220522_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='bg_status_documents_cfs',
            field=models.TextField(choices=[('PENDING', 'PENDING'), ('SENDED', 'SENDED')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='bg_status_documents_cfs',
            field=models.TextField(choices=[('PENDING', 'PENDING'), ('SENDED', 'SENDED')], default=None, null=True),
        ),
    ]
